### PR TITLE
Support multiple tags

### PR DESCRIPTION
**Pull request by Uyutaka**
square

### CODE REVIEW

**Comment by Uyutaka** [comment]
When a user clicks the tag button, should the user go to the list of items tagged it (using handleOnSearch)? 
Now, there is no transition when clicking the tag button.

**Comment by Sayter99** [comment]
good to have this feature. could you change to button shape to round as well?
[reference](https://ant.design/components/button/)

Thanks!

**Comment by Uyutaka** [comment]
I tried the square one. But, the button was like this.
I could not modify the padding. I tried adding spaces before and after the tag word. But, automatically removed them.
oval

**Comment by Sayter99** [comment]
I've pushed a commit that utilized button attribute called shape, you could try this. I think it looks a bit better.

**Comment by Uyutaka** [comment]
Ok, I will check it.

**Comment by Uyutaka** [comment]
@Sayter99 I checked your code. It looks much better. How about https://github.com/coloradocollective/S20_Team_6/pull/19#issuecomment-613076735

**Comment by Sayter99** [comment]
sounds good, go for it.

**Comment by Uyutaka** [comment]
ok

**Comment by Uyutaka** [comment]
@Sayter99 
I added the feature. If it is ok, could you merge?

**Comment by Sayter99** [comment]
I'll check it. Thank you.

**Pull request merged**
